name: Sample Workflow

on:
  push:
    branches: sharon_trunk_cicd
  workflow_dispatch:
  
env:
  IMAGE_NAME: ${{github.ref_name}}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        ref: 'main'
        
    - name: Set Release version env variable
      run: |
         echo "REL_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
             

    - name: Set Release version env variable
      run: |
         
         VERSION = $(echo ${REL_VERSION} |  awk -F'.' '{print $1"."$2"."$3+1}' |  sed s/[.]$//)
         echo Hello 
         echo $VERSION

    - name: update pom version
      run: |
        # do some operation that changes a file in the git repo
        mvn versions:set -DnewVersion=$REL_VERSION
             
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "Sharon-Manisha"
        git config user.email "<sharon@shiftx.ai>"   
        
    - name: create branch  
      run: |        
         git checkout -b sharon_trunk_patch
         #git push origin sharon_trunk_patch
         
    - name: commit code
      run: |
         # Stage the file, commit and push         
         git add pom.xml
         git commit -m "updated version in pom.xml"
         git push origin sharon_trunk_patch          
                     
    - name: create pull request
      run: gh pr create --reviewer VigneshIyappan -B main -H sharon_trunk_patch --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'  
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }} 