name: Sample Workflow

on:
  push:
    branches: sharon_trunk_cicd
  workflow_dispatch:
  
env:
  IMAGE_NAME: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   # - name: Fail if branch is not main
    #  if: github.ref != 'refs/heads/main'
     # run: |
        #  echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
         # exit 1
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
     
    - name: Set Release version env variable
      run: |
         echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
         
    - name: List Docker Images
      run: docker images
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
 
    - name: update pom version
      run: |
        # do some operation that changes a file in the git repo
        mvn versions:set -DnewVersion=4.1.7
       
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "Sharon-Manisha"
        git config user.email "<sharon@shiftx.ai>"                
    #- name: commit code
     # run: |
         # Stage the file, commit and push
         #git add pom.xml
         #git commit -m "updated version in pom.xml"
         #git push -u origin
         
    - uses: actions/checkout@v2
    - name: pull-request-action
      uses: Sharon-Manisha/GitActionsApp/pull-request-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        PULL_REQUEST_BRANCH: "main"
       
      