name: Sample Workflow

on:
  push:
    branches: sharon_trunk_cicd
  workflow_dispatch:
  
env:
  IMAGE_NAME: ${{github.ref_name}}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: update pom version
      run: |
        # do some operation that changes a file in the git repo
        mvn versions:set -DnewVersion=4.1.7
       
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "Sharon-Manisha"
        git config user.email "<sharon@shiftx.ai>"                
    #- name: commit code
     # run: |
         # Stage the file, commit and push
         #git add pom.xml
         #git commit -m "updated version in pom.xml"
         #git push -u origin
         
    - name: Create Pull Request
      id: cpr
      uses: ./
      with:
          commit-message: Update pom
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          title: '[Example] Update Pom'
          body: |
            Update Pom
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/Sharon-Manisha/GitActionsApp/create-pull-request
          labels: |
            report
            automated pr
          assignees: Sharon-Manisha
          reviewers: Sharon-Manisha
          draft: false
          branch: example-patches
          delete-branch: false  