name: Sample Workflow

on:
  push:
    branches: sharon_trunk_cicd
  workflow_dispatch:
  
env:
  IMAGE_NAME: ${{github.ref_name}}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: update pom version
      run: |
        # do some operation that changes a file in the git repo
        mvn versions:set -DnewVersion=4.1.8
       
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "Sharon-Manisha"
        git config user.email "<sharon@shiftx.ai>"                
    - name: commit code
      run: |
         # Stage the file, commit and push
         git add pom.xml
         git commit -m "updated version in pom.xml"
         git push -u origin
         
    - name: Run the Action
      uses: Sharon-Manisha/GitActionsApp@2.0.30
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        source_branch: sharon_trunk_cicd
        target_branch: main
        title: My pull request
        template: .github/PULL_REQUEST_TEMPLATE.md
        body: "**Automated pull request**"
        reviewer: Sharon-Manisha
        assignee: Sharon-Manisha
        label: enhancement
        milestone: My milestone
        draft: true
        old_string: "<!-- Add your description here -->"
        new_string: "** Automatic pull request**"
        get_diff: true
        ignore_users: "dependabot"
        allow_no_diff: false